// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjtpl7h-4Ykcp8ZxCBdxFtVkN6L-z_LHQ',
    appId: '1:766552240054:web:c91bfc4ff1ddf0176a5b17',
    messagingSenderId: '766552240054',
    projectId: 'chatum-5bd99',
    authDomain: 'chatum-5bd99.firebaseapp.com',
    storageBucket: 'chatum-5bd99.firebasestorage.app',
    measurementId: 'G-447ZNMQ932',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAOEuNhSis39aTD4pruOnL3RfuXhKxwt0',
    appId: '1:766552240054:android:1acae33e6a1453476a5b17',
    messagingSenderId: '766552240054',
    projectId: 'chatum-5bd99',
    storageBucket: 'chatum-5bd99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOOb4o6O7bqs-34dCOuRrjsHahhYAZ8UY',
    appId: '1:766552240054:ios:e510446b69c1f68b6a5b17',
    messagingSenderId: '766552240054',
    projectId: 'chatum-5bd99',
    storageBucket: 'chatum-5bd99.firebasestorage.app',
    iosBundleId: 'com.example.chatum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOOb4o6O7bqs-34dCOuRrjsHahhYAZ8UY',
    appId: '1:766552240054:ios:e510446b69c1f68b6a5b17',
    messagingSenderId: '766552240054',
    projectId: 'chatum-5bd99',
    storageBucket: 'chatum-5bd99.firebasestorage.app',
    iosBundleId: 'com.example.chatum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjtpl7h-4Ykcp8ZxCBdxFtVkN6L-z_LHQ',
    appId: '1:766552240054:web:e16a934f8582ec1f6a5b17',
    messagingSenderId: '766552240054',
    projectId: 'chatum-5bd99',
    authDomain: 'chatum-5bd99.firebaseapp.com',
    storageBucket: 'chatum-5bd99.firebasestorage.app',
    measurementId: 'G-F7NNWC777F',
  );
}
